# Generated by Django 5.2.5 on 2026-09-30 14:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField(verbose_name='texto')),
                ('media', models.FileField(blank=True, upload_to='posts/%Y/%m/', verbose_name='archivo multimedia')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de publicación')),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('body', models.TextField(max_length=1000, verbose_name='comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('approved', models.BooleanField(default=False, verbose_name='aprobado')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'ordering': ['created_at'],
            },
        ),
    ]
